# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in summaries.gemspec
gemspec

gem "rake", "~> 13.4"

gem "minitest", "~> 5.26"

gem "standard", "~> 1.55"

gem "rss"

gem "aws_lambda_ric"
