# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in articles.gemspec
gemspec

gem "rake", "~> 13.3"

gem "minitest", "~> 5.16"

gem "standard", "~> 1.54"

gem "nokogiri"

gem "aws_lambda_ric"
